// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Mx48x1_6w1Rx2weHI7moxHHytBePKDY',
    appId: '1:221714047642:web:e822804594aa50d4dab523',
    messagingSenderId: '221714047642',
    projectId: 'ethi-wallet',
    authDomain: 'ethi-wallet.firebaseapp.com',
    storageBucket: 'ethi-wallet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIaCYAf4eS0YwzshdqMxodjHLhjewzBP8',
    appId: '1:221714047642:android:8dc760e6fc76a835dab523',
    messagingSenderId: '221714047642',
    projectId: 'ethi-wallet',
    storageBucket: 'ethi-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPRH4YZLIIUyLRBiRTc5OTKS37U9Fbzj4',
    appId: '1:221714047642:ios:205696169edc20b0dab523',
    messagingSenderId: '221714047642',
    projectId: 'ethi-wallet',
    storageBucket: 'ethi-wallet.firebasestorage.app',
    iosBundleId: 'com.example.ethioWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPRH4YZLIIUyLRBiRTc5OTKS37U9Fbzj4',
    appId: '1:221714047642:ios:205696169edc20b0dab523',
    messagingSenderId: '221714047642',
    projectId: 'ethi-wallet',
    storageBucket: 'ethi-wallet.firebasestorage.app',
    iosBundleId: 'com.example.ethioWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Mx48x1_6w1Rx2weHI7moxHHytBePKDY',
    appId: '1:221714047642:web:c8e208e58367fdbfdab523',
    messagingSenderId: '221714047642',
    projectId: 'ethi-wallet',
    authDomain: 'ethi-wallet.firebaseapp.com',
    storageBucket: 'ethi-wallet.firebasestorage.app',
  );
}
